import Head from 'next/head'
import { Inter } from 'next/font/google'
import { SetStateAction, useState } from 'react'
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] })

interface User{
  name: string
}

export default function Home() {
  const [user, setUser] = useState<User | null>(null);
  return (
    <>
      <Head>
        <title>Simples Testes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Site Simples</h1>
        <button onClick={ async () => {
          const response: SetStateAction<any> = await axios.post('/api/mongo') as unknown;
          const { data } = response;
          const user = data as User;
          setUser(user);
        }}>Click Aqui</button>
        <div>{ user && user.name}</div>
      </main>
    </>
  )
}
